/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./compat/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        xs: "320px",
        "xs-max": { max: "340px" },
        sm: "420px",
        "sm-max": { max: "420px" },
        as: "400px",
        "as-max": { max: "400px" },
        md: "768px",
        "md-max": { max: "768px" },
        lg: "992px",
        "lg-max": { max: "992px" },
        xl: "1200px",
        "xl-max": { max: "1200px" },
        "2xl": "1320px",
        "2xl-max": { max: "1320px" },
        "3xl": "1600px",
        "3xl-max": { max: "1600px" },
        "4xl": "1850px",
        "4xl-max": { max: "1850px" },
      },
      responsive: {
        breakpoints: {
          xs: 340,
          sm: 420,
          md: 768,
        },
        space: {
          xs: 10,
          sm: 12,
          base: 16,
          md: 24,
        },
        cardPadding: {
          xs: 12,
          sm: 14,
          base: 18,
          md: 24,
        },
        radius: {
          xs: 8,
          sm: 12,
          base: 12,
          md: 16,
        },
        font: {
          xs: { xs: 10, sm: 11, base: 11, md: 11 },
          sm: { xs: 11, sm: 12, base: 12, md: 12 },
          md: { xs: 12, sm: 13, base: 14, md: 14 },
          lg: { xs: 14, sm: 15, base: 16, md: 16 },
          xl: { xs: 17, sm: 19, base: 22, md: 22 },
          xxl: { xs: 20, sm: 22, base: 24, md: 24 },
        },
        icon: {
          sm: { xs: 12, sm: 14, base: 14, md: 14 },
          md: { xs: 16, sm: 18, base: 18, md: 18 },
          lg: { xs: 24, sm: 28, base: 32, md: 32 },
          xl: { xs: 48, sm: 56, base: 64, md: 64 },
        },
      },
      colors: {
        primary: {
          50: "#F5F3FF",
          100: "#EDE9FE",
          200: "#DDD6FE",
          300: "#C4B5FD",
          400: "#A78BFA",
          500: "#8B5CF6",
          600: "#7C3AED",
          700: "#6D28D9",
          800: "#5B21B6",
          900: "#4C1D95",
        },
        secondary: "#FFFFFF",
        primarytext: "#121212",
        inactiveTabLabel: "#9CA3AF",
      },
      fontFamily: {
        pthin: ["Poppins-Thin", "sans-serif"],
        pextralight: ["Poppins-ExtraLight", "sans-serif"],
        plight: ["Poppins-Light", "sans-serif"],
        pregular: ["Poppins-Regular", "sans-serif"],
        pmedium: ["Poppins-Medium", "sans-serif"],
        psemibold: ["Poppins-SemiBold", "sans-serif"],
        pbold: ["Poppins-Bold", "sans-serif"],
        pextrabold: ["Poppins-ExtraBold", "sans-serif"],
        pblack: ["Poppins-Black", "sans-serif"],
      },
    },
  },
  plugins: [],
};
