import React, { useState, useEffect, useRef } from "react";
import {
  TextInput,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Alert,
  Image,
  ActivityIndicator,
  FlatList,
  KeyboardAvoidingView,
  Platform,
  webStyle,
} from "react-native";
import { Category, Material } from "@/types/product";
import MaterialService from "@/services/MaterialService";
import CategoryService from "@/services/CategoryService";
import KeyboardAwareModal from "./KeyboardAwareModal";
import FloatingDropdown from "./FloatingDropdown";
import FloatingInput from "./FloatingInput";
import FloatingTextarea from "./FloatingTextarea";
import PartyService from "@/services/PartyService";
import { Party } from "@/types/party";
import { useAuthStore } from "@/store/auth.store";
import { getDeviceMetrics } from "@/utils/responsive";
import { splitAmountAndUnit } from "@/utils/productPricing";
import { useRouter } from "next/router";

const { width, isXs: isSmallScreen } = getDeviceMetrics();

interface ProductFormProps {
  existingProduct?: any;
  isEditMode?: boolean;
}

interface SpecField {
  key: string;
  value: string;
  unit: string;
  isDefault: boolean;
}

const DIMENSION_UNITS = ["inch", "mm", "m", "cm", "ft"];
const WEIGHT_UNITS = ["g", "kg", "lb", "oz"];
const RATE_UNITS = ["kg", "g", "pcs", "set", "pair"];
const PRICE_UNITS = ["pcs", "set", "pair", "kg", "g"];
const PRODUCT_DETAIL_INTERNAL_KEYS = new Set(["rate", "rateUnit", "priceUnit"]);

const DEFAULT_SPEC_FIELDS: SpecField[] = [
  { key: "price", value: "", unit: "pcs", isDefault: true },
  { key: "weight", value: "", unit: "g", isDefault: true },
  { key: "height", value: "", unit: "inch", isDefault: true },
  { key: "width", value: "", unit: "inch", isDefault: true },
  { key: "depth", value: "", unit: "inch", isDefault: true },
  { key: "length", value: "", unit: "inch", isDefault: true },
];

const generateDesignCode = (productName?: string): string => {
  if (productName && productName.trim()) {
    const prefix = productName
      .trim()

      .replace(/[^A-Z0-9\s]/g, "")
      .split(/\s+/)
      .map((w) => w.substring(0, 3))
      .slice(0, 3)
      .join("-");
    const rand = Math.floor(1000 + Math.random() * 9000);
    return `${prefix}-${rand}`;
  }
  const now = new Date();
  const y = now.getFullYear().toString().slice(-2);
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const d = String(now.getDate()).padStart(2, "0");
  const rand = Math.random().toString(36).substring(2, 6);
  return `SMA-${y}${m}${d}-${rand}`;
};

const extractList = <T,>(response: any): T[] => {
  const data = response?.data?.data ?? response?.data ?? [];
  return Array.isArray(data) ? data : [];
};

const extractEntity = <T,>(response: any): T | null => {
  return (response?.data?.data ?? response?.data ?? null) as T | null;
};

const ProductForm: React.FC<ProductFormProps> = ({
  existingProduct,
  isEditMode = false,
}) => {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const BASE_URL =
    process.env.NEXT_PUBLIC_API_URL ||
    process.env.EXPO_PUBLIC_API_URL ||
    "";
  const API_ROOT = BASE_URL
    ? `${BASE_URL.replace(/\/$/, "")}/api/sanraj-metal-arts`
    : "/api/sanraj-metal-arts";
  const [formDetails, setFormDetails] = useState({
    name: "",
    description: "",
    categoryTypeId: "",
    materialId: "",
    urlkey: "",
    designCode: "",
    partiesIds: [] as string[],
    stock: 0,
  });

  const [mediaFiles, setMediaFiles] = useState<any[]>([]);
  const [selectedPartys, setSelectedPartys] = useState<string[]>([]);
  const [showPartysModal, setShowPartysModal] = useState(false);
  const [partys, setPartys] = useState<Party[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [materials, setMaterials] = useState<Material[]>([]);
  const [imageProcessing, setImageProcessing] = useState(false);
  const [productRate, setProductRate] = useState("");
  const [productRateUnit, setProductRateUnit] = useState("kg");
  const [productDetailFields, setProductDetailFields] =
    useState<SpecField[]>(DEFAULT_SPEC_FIELDS);
  const [activeUnitDropdown, setActiveUnitDropdown] = useState<number | null>(
    null,
  );

  const [fetchingPartys, setFetchingPartys] = useState(false);
  const [partySearchQuery, setPartySearchQuery] = useState("");
  const partySearchTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(
    null,
  );

  useEffect(() => {
    if (!isEditMode && !formDetails.designCode) {
      const code = generateDesignCode();
      setFormDetails((prev) => ({ ...prev, designCode: code }));
    }
  }, [formDetails.designCode, isEditMode]);

  const autoGenerateDesignCode = () => {
    if (formDetails.name.trim()) {
      const code = generateDesignCode(formDetails.name);
      setFormDetails((prev) => ({ ...prev, designCode: code }));
    }
  };

  const loadData = useRef(async () => {
    try {
      setIsLoading(true);
      setError("");

      const [categoriesRes, materialsRes] = await Promise.all([
        CategoryService.fetchAllCategory(),
        MaterialService.fetchAllMaterial(),
      ]);

      setCategories(extractList<Category>(categoriesRes));
      setMaterials(extractList<Material>(materialsRes));

      await fetchParties();
    } catch (err) {
      console.error("Error loading data:", err);
      setError("Failed to load form data");
    } finally {
      setIsLoading(false);
    }
  });

  const fetchParties = async (isLoadMore = false, searchText = "") => {
    try {
      setFetchingPartys(true);
      const res: any = await PartyService.fetchPartiesDropdown();
      const partyList = PartyService.extractPartyList<Party>(res);
      const filtered = searchText.trim()
        ? partyList.filter((party) =>
            party.name?.toLowerCase().includes(searchText.toLowerCase()),
          )
        : partyList;
      setPartys(filtered);
    } catch (err: any) {
      console.error("Error fetching parties:", err);
    } finally {
      setFetchingPartys(false);
    }
  };

  const handlePartySearch = (searchText: string) => {
    setPartySearchQuery(searchText);
    if (partySearchTimeoutRef.current) {
      clearTimeout(partySearchTimeoutRef.current);
    }
    partySearchTimeoutRef.current = setTimeout(() => {
      fetchParties(false, searchText);
    }, 500);
  };

  const handleClearPartySearch = () => {
    setPartySearchQuery("");
    if (partySearchTimeoutRef.current) {
      clearTimeout(partySearchTimeoutRef.current);
    }
    fetchParties();
  };

  useEffect(() => {
    return () => {
      if (partySearchTimeoutRef.current) {
        clearTimeout(partySearchTimeoutRef.current);
      }
    };
  }, []);

  useEffect(() => {
    const initializeForm = async () => {
      await loadData.current();
      if (isEditMode && existingProduct) {
        setFormDetails({
          name: existingProduct.name || "",
          description: existingProduct.description || "",
          categoryTypeId: existingProduct?.categoryTypeId || "",
          materialId: existingProduct?.materialId || "",
          urlkey: existingProduct.urlkey || "",
          designCode: existingProduct.designCode || "",
          partiesIds: existingProduct.partiesIds || [],
          stock: existingProduct.stock || 0,
        });
        setSelectedPartys(existingProduct.partiesIds || []);

        if (existingProduct.productDetail?.rate) {
          const rateInfo = splitAmountAndUnit(
            existingProduct.productDetail.rate,
            existingProduct.productDetail.rateUnit || "kg",
          );
          setProductRate(rateInfo.value);
          setProductRateUnit(rateInfo.unit || "kg");
        }

        if (existingProduct.productDetail) {
          const fields: SpecField[] = [...DEFAULT_SPEC_FIELDS];
          Object.entries(existingProduct.productDetail).forEach(
            ([key, val]) => {
              if (PRODUCT_DETAIL_INTERNAL_KEYS.has(key)) return;

              const strVal = String(val);
              const defaultIdx = fields.findIndex((f) => f.key === key);
              if (defaultIdx !== -1) {
                if (
                  key === "price" ||
                  key === "weight" ||
                  key === "height" ||
                  key === "width" ||
                  key === "depth" ||
                  key === "length"
                ) {
                  const parsed = splitAmountAndUnit(
                    strVal,
                    fields[defaultIdx].unit,
                  );
                  fields[defaultIdx].value = parsed.value;
                  fields[defaultIdx].unit =
                    parsed.unit || fields[defaultIdx].unit;
                } else {
                  fields[defaultIdx].value = strVal;
                }
              } else {
                fields.push({
                  key,
                  value: strVal,
                  unit: "",
                  isDefault: false,
                });
              }
            },
          );
          setProductDetailFields(fields);
        }

        if (existingProduct.images && existingProduct.images.length > 0) {
          const existingMedia = existingProduct.images.map(
            (img: any, index: number) => ({
              id: `existing-${index}`,
              url: img,
              uri: img,
              type: "image",
              name: `Product Image ${index + 1}`,
              isNew: false,
            }),
          );
          setMediaFiles(existingMedia);
        }
      }
    };
    initializeForm();
  }, [existingProduct, isEditMode]);

  const resetForm = () => {
    setFormDetails({
      name: "",
      description: "",
      categoryTypeId: "",
      materialId: "",
      urlkey: "",
      designCode: generateDesignCode(),
      partiesIds: [],
      stock: 0,
    });
    setMediaFiles([]);
    setSelectedPartys([]);
    setProductRate("");
    setProductRateUnit("kg");
    setProductDetailFields([...DEFAULT_SPEC_FIELDS]);
    setError("");
    setSuccess("");
  };

  const handleChange = (field: string, value: string | number) => {
    setFormDetails((prev) => ({ ...prev, [field]: value }));
  };

  const generateUrlKey = () => {
    if (formDetails.name) {
      const baseKey = formDetails.name
        .toLowerCase()
        .replace(/[^\w\s]/gi, "")
        .replace(/\s+/g, "-");
      const randomNum = Math.floor(100000 + Math.random() * 900000);
      const urlKey = `${baseKey}-${randomNum}`;
      handleChange("urlkey", urlKey);
    }
  };

  const handleNameBlur = () => {
    generateUrlKey();
    if (!formDetails.designCode || !isEditMode) {
      autoGenerateDesignCode();
    }
  };

  const handleAddNewCategory = async (
    name: string,
  ): Promise<{ id: string; name: string } | null> => {
    try {
      const res = await CategoryService.addNewCategory({ name });
      if (res.success) {
        const newCat = extractEntity<Category>(res);
        if (!newCat) return null;
        setCategories((prev) => [...prev, newCat]);
        return { id: newCat.id, name: newCat.name };
      }
      return null;
    } catch (err) {
      console.error("Error adding category:", err);
      throw err;
    }
  };

  const handleAddNewMaterial = async (
    name: string,
  ): Promise<{ id: string; name: string } | null> => {
    try {
      const res = await MaterialService.addNewMaterial({ name } as any);
      if (res.success) {
        const newMat = extractEntity<Material>(res);
        if (!newMat) return null;
        setMaterials((prev) => [...prev, newMat]);
        if (!newMat.id) return null;
        return { id: newMat.id, name: newMat.name };
      }
      return null;
    } catch (err) {
      console.error("Error adding material:", err);
      throw err;
    }
  };

  const pickImages = async () => {
    if (loading || imageProcessing) return;

    Alert.alert("Select Images", "Choose source", [
      {
        text: "Gallery",
        onPress: async () => {
          try {
            setImageProcessing(true);
            const { status } =
              await ImagePicker.requestMediaLibraryPermissionsAsync();
            if (status !== "granted") {
              Alert.alert("Permission required", "Need camera roll access");
              setImageProcessing(false);
              return;
            }
            const result = await ImagePicker.launchImageLibraryAsync({
              mediaTypes: ImagePicker.MediaTypeOptions.Images,
              allowsMultipleSelection: true,
              quality: 0.8,
            });
            if (!result.canceled) {
              const newImages = result.assets.map((img, index) => ({
                id: `${Date.now()}-${index}`,
                uri: img.uri,
                originalUri: img.uri,
                type: "image",
                name: `product_${Date.now()}_${index}.jpg`,
                width: img.width,
                height: img.height,
                originalWidth: img.width,
                originalHeight: img.height,
                size: img.fileSize || 0,
                mime: img.mimeType || "image/jpeg",
                isNew: true,
                aspectRatio:
                  img.width && img.height ? img.width / img.height : 1,
              }));
              setMediaFiles((prev) => [...prev, ...newImages]);
            }
          } catch (e) {
            console.error("Image picker error:", e);
            Alert.alert("Error", "Failed to pick images");
          } finally {
            setImageProcessing(false);
          }
        },
      },
      {
        text: "Camera",
        onPress: async () => {
          try {
            setImageProcessing(true);
            const { status } =
              await ImagePicker.requestCameraPermissionsAsync();
            if (status !== "granted") {
              Alert.alert("Permission required", "Need camera access");
              setImageProcessing(false);
              return;
            }
            const result = await ImagePicker.launchCameraAsync({
              quality: 0.8,
            });
            if (!result.canceled) {
              const img = result.assets[0];
              const newImage = {
                id: `${Date.now()}`,
                uri: img.uri,
                originalUri: img.uri,
                type: "image",
                name: `product_${Date.now()}.jpg`,
                width: img.width,
                height: img.height,
                originalWidth: img.width,
                originalHeight: img.height,
                size: img.fileSize || 0,
                mime: img.mimeType || "image/jpeg",
                isNew: true,
                aspectRatio:
                  img.width && img.height ? img.width / img.height : 1,
              };
              setMediaFiles((prev) => [...prev, newImage]);
            }
          } catch (e) {
            console.error("Camera error:", e);
            Alert.alert("Error", "Failed to take photo");
          } finally {
            setImageProcessing(false);
          }
        },
      },
      { text: "Cancel", style: "cancel" },
    ]);
  };

  const removeMedia = (id: string) => {
    if (loading || imageProcessing) return;
    Alert.alert("Remove Image", "Are you sure?", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Remove",
        style: "destructive",
        onPress: () => {
          setMediaFiles((prev) => prev.filter((img) => img.id !== id));
        },
      },
    ]);
  };

  const handleSubmit = async () => {
    if (loading || imageProcessing) return;
    setLoading(true);
    setSubmitted(true);
    setError("");

    try {
      if (!formDetails.name.trim()) {
        setError("Product name is required");
        setLoading(false);
        return;
      }
      if (!formDetails.designCode.trim()) {
        setError("Design code is required");
        setLoading(false);
        return;
      }
      if (!formDetails.categoryTypeId) {
        setError("Category is required");
        setLoading(false);
        return;
      }
      if (!formDetails.materialId) {
        setError("Material is required");
        setLoading(false);
        return;
      }
      if (selectedPartys.length === 0) {
        setError("At least one party is required");
        setLoading(false);
        return;
      }

      const formData = new FormData();
      formData.append("name", formDetails.name.trim());
      formData.append("description", formDetails.description || "");
      formData.append("categoryTypeId", formDetails.categoryTypeId);
      formData.append("materialId", formDetails.materialId || "");
      formData.append("urlkey", formDetails.urlkey);
      formData.append("designCode", formDetails.designCode);
      formData.append("stock", String(formDetails.stock));
      formData.append("partiesIds", JSON.stringify(selectedPartys));

      const productDetails: any = {};
      if (productRate.trim()) {
        productDetails.rate = productRateUnit
          ? `${productRate.trim()}/${productRateUnit}`
          : productRate.trim();
      }
      productDetailFields.forEach((field) => {
        if (field.key && field.value) {
          if (
            field.key === "weight" ||
            field.key === "height" ||
            field.key === "width" ||
            field.key === "depth" ||
            field.key === "length"
          ) {
            productDetails[field.key] = `${field.value} ${field.unit}`;
          } else if (field.key === "price") {
            productDetails[field.key] = field.unit
              ? `${field.value} ${field.unit}`
              : field.value;
          } else {
            productDetails[field.key] = field.unit
              ? `${field.value} ${field.unit}`
              : field.value;
          }
        }
      });
      formData.append("productDetail", JSON.stringify(productDetails));

      const existingImages: string[] = [];
      const newImages: any[] = [];
      mediaFiles.forEach((img) => {
        if (img.isNew) {
          newImages.push(img);
        } else {
          existingImages.push(img.uri);
        }
      });

      if (isEditMode) {
        formData.append("existingImages", JSON.stringify(existingImages));
      }
      newImages.forEach((img) => {
        if (img.originalUri) {
          formData.append("images", {
            uri: img.originalUri,
            name: img.name || `product_${Date.now()}.jpg`,
            type: img.mime || "image/jpeg",
          } as any);
        }
      });

      const url = isEditMode
        ? `${API_ROOT}/products/${existingProduct.id}`
        : `${API_ROOT}/products`;
      const { session } = useAuthStore.getState();
      const token = session?.token;
      const response = await fetch(url, {
        method: isEditMode ? "PUT" : "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/json",
        },
        body: formData,
      });

      const data = await response.json();
      if (data.success) {
        setSuccess("Product saved successfully");
        setSubmitted(false);
        setError("");
        if (!isEditMode) {
          resetForm();
        }
        setTimeout(() => {
          router.back();
        }, 1500);
      } else {
        setError(data.message || data.error || "Failed to save product");
      }
    } catch (err: any) {
      console.error("Submit error:", err);
      setError(err.message || "Network error occurred");
    } finally {
      setLoading(false);
    }
  };

  const handlePartySelect = (partyId: string) => {
    setSelectedPartys((prev) => {
      if (prev.includes(partyId)) {
        return prev.filter((id) => id !== partyId);
      }
      return [...prev, partyId];
    });
  };

  const addProductDetailField = () => {
    setProductDetailFields([
      ...productDetailFields,
      { key: "", value: "", unit: "", isDefault: false },
    ]);
  };

  const removeProductDetailField = (index: number) => {
    const field = productDetailFields[index];
    if (field.isDefault) {
      Alert.alert("Cannot Remove", "Default specifications cannot be removed.");
      return;
    }
    Alert.alert("Remove Specification", "Are you sure?", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Remove",
        style: "destructive",
        onPress: () => {
          const newFields = [...productDetailFields];
          newFields.splice(index, 1);
          setProductDetailFields(newFields);
        },
      },
    ]);
  };

  const updateSpecField = (
    index: number,
    field: "key" | "value" | "unit",
    val: string,
  ) => {
    const newFields = [...productDetailFields];
    newFields[index] = { ...newFields[index], [field]: val };
    setProductDetailFields(newFields);
  };

  const getUnitsForKey = (key: string): string[] => {
    switch (key) {
      case "price":
        return PRICE_UNITS;
      case "weight":
        return WEIGHT_UNITS;
      case "height":
      case "width":
      case "depth":
      case "length":
        return DIMENSION_UNITS;
      default:
        return [...DIMENSION_UNITS, ...WEIGHT_UNITS, "pcs", "set", "pair"];
    }
  };

  const getSpecFieldLabel = (field: SpecField) => {
    if (!field.isDefault) return field.key || "Custom Field";
    if (field.key === "price") return "Price Per Piece";
    return field.key.charAt(0).toUpperCase() + field.key.slice(1);
  };

  if (isLoading) {
    return (
      <div style={webStyle(styles.loadingContainer)}>
        <ActivityIndicator size="large" color="#8B5CF6" />
        <span style={webStyle(styles.loadingText)}>Loading...</span>
      </div>
    );
  }

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === "ios" ? "padding" : "height"}
      style={{ flex: 1 }}
    >
      <ScrollView
        style={styles.container}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
        automaticallyAdjustKeyboardInsets
      >
        <div id={"infoCard"} style={webStyle(styles.infoCard)}>
          <Icon name="information-outline" size={20} color="#8B5CF6" />
          <span style={webStyle(styles.infoText)}>
            {isEditMode
              ? "Edit product details below"
              : "Fill all required fields to create a new product"}
          </span>
        </div>

        {error ? (
          <div style={webStyle(styles.errorBanner)}>
            <Icon name="alert-circle" size={20} color="#DC2626" />
            <span style={webStyle(styles.errorBannerText)}>{error}</span>
            <TouchableOpacity onPress={() => setError("")}>
              <Icon name="close" size={20} color="#DC2626" />
            </TouchableOpacity>
          </div>
        ) : null}

        {success ? (
          <div style={webStyle(styles.successBanner)}>
            <Icon name="check-circle" size={20} color="#059669" />
            <span style={webStyle(styles.successBannerText)}>{success}</span>
          </div>
        ) : null}

        {/* Basic Information */}
        <div style={webStyle(styles.section)}>
          <div style={webStyle(styles.sectionHeader)}>
            <Icon name="tag-outline" size={22} color="#8B5CF6" />
            <span style={webStyle(styles.sectionTitle)}>Product Details</span>
          </div>
          <div style={webStyle(styles.sectionContent)}>
            <FloatingInput
              label="Product Name"
              required={true}
              value={formDetails.name}
              onChangeText={(val) => handleChange("name", val)}
              onBlur={handleNameBlur}
              leftIcon="tag"
              error={
                !formDetails.name.trim() && submitted
                  ? "Product name is required"
                  : undefined
              }
              placeholder="Golden Elephant Statue"
              autoCapitalize="words"
              returnKeyType="next"
              editable={!loading}
            />

            <div style={webStyle(styles.rowSpaced)}>
              <div style={webStyle(styles.halfField)}>
                <FloatingInput
                  label="Design Code"
                  required={true}
                  value={formDetails.designCode}
                  onChangeText={(val) => handleChange("designCode", val)}
                  leftIcon="pound"
                  rightIcon="refresh"
                  onRightIconPress={autoGenerateDesignCode}
                  placeholder="Auto from name"
                  error={
                    !formDetails.designCode.trim() && submitted
                      ? "Design code is required"
                      : undefined
                  }
                  autoCapitalize="characters"
                  helperText="Auto from product name"
                  editable={!loading}
                />
              </div>
              <div style={webStyle(styles.halfField)}>
                <FloatingInput
                  label="URL Key"
                  required={true}
                  value={formDetails.urlkey}
                  onChangeText={(val) => handleChange("urlkey", val)}
                  leftIcon="link"
                  rightIcon="refresh"
                  onRightIconPress={generateUrlKey}
                  placeholder="auto-generate"
                  error={
                    !formDetails.urlkey.trim() && submitted
                      ? "URL key is required"
                      : undefined
                  }
                  autoCapitalize="none"
                  autoCorrect={false}
                  editable={!loading}
                />
              </div>
            </div>

            <div style={webStyle(styles.rowSpaced)}>
              <div style={webStyle(styles.halfField)}>
                <FloatingDropdown
                  label="Category"
                  required={true}
                  value={formDetails.categoryTypeId}
                  items={categories.map((cat) => ({
                    id: cat.id,
                    name: cat.name,
                  }))}
                  placeholder="Select a category"
                  onSelect={(val) => handleChange("categoryTypeId", val)}
                  searchable={true}
                  disabled={(categories.length === 0 && isLoading) || loading}
                  error={
                    !formDetails.categoryTypeId && submitted
                      ? "Category is required"
                      : undefined
                  }
                  onAddNew={handleAddNewCategory}
                  addNewLabel="Category"
                />
              </div>
              <div style={webStyle(styles.halfField)}>
                <FloatingDropdown
                  label="Material"
                  required={true}
                  value={formDetails.materialId}
                  items={materials
                    .map((mat) => ({
                      id: mat.id || "",
                      name: mat.name,
                    }))
                    .filter((mat) => mat.id)}
                  placeholder="Select material"
                  onSelect={(val) => handleChange("materialId", val)}
                  searchable={true}
                  disabled={(materials.length === 0 && isLoading) || loading}
                  error={
                    !formDetails.materialId && submitted
                      ? "Material is required"
                      : undefined
                  }
                  onAddNew={handleAddNewMaterial}
                  addNewLabel="Material"
                />
              </div>
            </div>

            <FloatingInput
              label="Stock Quantity"
              value={
                formDetails.stock === 0 ? "" : formDetails.stock.toString()
              }
              onChangeText={(val) => handleChange("stock", parseInt(val) || 0)}
              leftIcon="package"
              placeholder="0"
              keyboardType="number-pad"
              editable={!loading}
            />

            <FloatingTextarea
              label="Description"
              value={formDetails.description}
              onChangeText={(val) => handleChange("description", val)}
              placeholder="Describe the product features, craftsmanship, materials used..."
              rows={4}
              maxLength={500}
              helperText="Describe your product in detail (max 500 characters)"
              enableAIRewrite={true}
              editable={!loading}
            />
          </div>
        </div>

        {/* Product Images */}
        <div style={webStyle(styles.section)}>
          <div style={webStyle(styles.sectionHeader)}>
            <Icon name="image-outline" size={22} color="#8B5CF6" />
            <span style={webStyle(styles.sectionTitle)}>Images</span>
            {mediaFiles.length > 0 && (
              <div style={webStyle(styles.countBadge)}>
                <span style={webStyle(styles.countText)}>{mediaFiles.length}</span>
              </div>
            )}
          </div>
          <div style={webStyle(styles.sectionContent)}>
            {mediaFiles.length > 0 ? (
              <div style={webStyle(styles.mediaGrid)}>
                {mediaFiles.map((item, index) => (
                  <div
                    style={webStyle(styles.mediaItem)}
                    key={item.uri || item.url || index}
                  >
                    <Image
                      source={{ uri: item.uri || item.url }}
                      style={styles.mediaImage}
                    />
                    <TouchableOpacity
                      style={styles.removeMediaButton}
                      onPress={() => removeMedia(item.id)}
                    >
                      <Icon name="close" size={14} color="#FFFFFF" />
                    </TouchableOpacity>
                    <span style={webStyle(styles.mediaIndex)}>{index + 1}</span>
                  </div>
                ))}
              </div>
            ) : (
              <TouchableOpacity
                style={styles.emptyMedia}
                onPress={pickImages}
                disabled={loading || imageProcessing}
              >
                <Icon name="image-outline" size={36} color="#D1D5DB" />
                <span style={webStyle(styles.emptyTitle)}>No images added</span>
              </TouchableOpacity>
            )}
            <TouchableOpacity
              style={[styles.uploadButton, loading && { opacity: 0.5 }]}
              onPress={pickImages}
              disabled={loading || imageProcessing}
            >
              {loading ? (
                <ActivityIndicator size="small" color="#8B5CF6" />
              ) : (
                <>
                  <Icon name="plus" size={18} color="#8B5CF6" />
                  <span style={webStyle(styles.uploadText)}>Add Images</span>
                </>
              )}
            </TouchableOpacity>
          </div>
        </div>

        {/* Specifications */}
        <div style={webStyle(styles.section)}>
          <div style={webStyle(styles.sectionHeader)}>
            <Icon name="file-document-outline" size={22} color="#8B5CF6" />
            <span style={webStyle(styles.sectionTitle)}>Specifications</span>
            <TouchableOpacity
              style={styles.addButton}
              onPress={addProductDetailField}
            >
              <Icon name="plus" size={16} color="#FFFFFF" />
            </TouchableOpacity>
          </div>
          <div style={webStyle(styles.sectionContent)}>
            <div style={webStyle(styles.specFieldContainer)}>
              <div style={webStyle(styles.specFieldHeader)}>
                <span style={webStyle(styles.specFieldLabel)}>Product Rate</span>
              </div>
              <div style={webStyle(styles.specFieldRow)}>
                <TextInput
                  style={[styles.specInput, { flex: 1 }]}
                  placeholder="0.00"
                  placeholderTextColor="#9CA3AF"
                  value={productRate}
                  onChangeText={setProductRate}
                  keyboardType="decimal-pad"
                  editable={!loading}
                />
                <div style={webStyle(styles.unitBadge)}>
                  <span style={webStyle(styles.unitBadgeText)}>₹</span>
                </div>
                <TouchableOpacity
                  style={styles.unitPickerButton}
                  onPress={() =>
                    setActiveUnitDropdown(activeUnitDropdown === -1 ? null : -1)
                  }
                >
                  <span style={webStyle(styles.unitPickerText)}>/{productRateUnit}</span>
                  <Icon
                    name={
                      activeUnitDropdown === -1 ? "chevron-up" : "chevron-down"
                    }
                    size={14}
                    color="#6B7280"
                  />
                </TouchableOpacity>
              </div>
              {activeUnitDropdown === -1 && (
                <div style={webStyle(styles.unitDropdown)}>
                  {RATE_UNITS.map((unit) => (
                    <TouchableOpacity
                      key={unit}
                      style={[
                        styles.unitOption,
                        productRateUnit === unit && styles.unitOptionSelected,
                      ]}
                      onPress={() => {
                        setProductRateUnit(unit);
                        setActiveUnitDropdown(null);
                      }}
                    >
                      <span
                        style={webStyle([
                          styles.unitOptionText,
                          productRateUnit === unit &&
                            styles.unitOptionTextSelected,
                        ])}
                      >
                        {unit}
                      </span>
                      {productRateUnit === unit && (
                        <Icon name="check" size={14} color="#8B5CF6" />
                      )}
                    </TouchableOpacity>
                  ))}
                </div>
              )}
            </div>

            {productDetailFields.map((field, index) => {
              const isPriceField = field.key === "price";
              const units = getUnitsForKey(field.key);
              const showUnitPicker = field.isDefault && units.length > 0;

              return (
                <div key={index} style={webStyle(styles.specFieldContainer)}>
                  <div style={webStyle(styles.specFieldHeader)}>
                    <span style={webStyle(styles.specFieldLabel)}>
                      {getSpecFieldLabel(field)}
                    </span>
                    {!field.isDefault && (
                      <TouchableOpacity
                        style={styles.removeSpecBtn}
                        onPress={() => removeProductDetailField(index)}
                      >
                        <Icon
                          name="trash-can-outline"
                          size={16}
                          color="#EF4444"
                        />
                      </TouchableOpacity>
                    )}
                  </div>

                  <div style={webStyle(styles.specFieldRow)}>
                    {!field.isDefault && (
                      <TextInput
                        style={[styles.specInput, { flex: 1 }]}
                        placeholder="Field name"
                        placeholderTextColor="#9CA3AF"
                        value={field.key}
                        onChangeText={(val) =>
                          updateSpecField(index, "key", val)
                        }
                      />
                    )}

                    <TextInput
                      style={[styles.specInput, { flex: 1 }]}
                      placeholder={
                        isPriceField ? "0.00" : `Enter ${field.key || "value"}`
                      }
                      placeholderTextColor="#9CA3AF"
                      value={field.value}
                      onChangeText={(val) =>
                        updateSpecField(index, "value", val)
                      }
                      keyboardType={
                        isPriceField ||
                        field.key === "weight" ||
                        field.key === "height" ||
                        field.key === "width" ||
                        field.key === "depth" ||
                        field.key === "length"
                          ? "decimal-pad"
                          : "default"
                      }
                    />

                    {isPriceField && (
                      <div style={webStyle(styles.unitBadge)}>
                        <span style={webStyle(styles.unitBadgeText)}>₹</span>
                      </div>
                    )}

                    {showUnitPicker && (
                      <TouchableOpacity
                        style={styles.unitPickerButton}
                        onPress={() =>
                          setActiveUnitDropdown(
                            activeUnitDropdown === index ? null : index,
                          )
                        }
                      >
                        <span style={webStyle(styles.unitPickerText)}>{field.unit}</span>
                        <Icon
                          name={
                            activeUnitDropdown === index
                              ? "chevron-up"
                              : "chevron-down"
                          }
                          size={14}
                          color="#6B7280"
                        />
                      </TouchableOpacity>
                    )}

                    {!field.isDefault && (
                      <TouchableOpacity
                        style={styles.unitPickerButton}
                        onPress={() =>
                          setActiveUnitDropdown(
                            activeUnitDropdown === index ? null : index,
                          )
                        }
                      >
                        <span style={webStyle(styles.unitPickerText)}>
                          {field.unit ? field.unit : "UNIT"}
                        </span>
                        <Icon name="chevron-down" size={14} color="#6B7280" />
                      </TouchableOpacity>
                    )}
                  </div>

                  {activeUnitDropdown === index && (
                    <div style={webStyle(styles.unitDropdown)}>
                      {(field.isDefault
                        ? units
                        : [
                            ...DIMENSION_UNITS,
                            ...WEIGHT_UNITS,
                            "pcs",
                            "set",
                            "pair",
                            "",
                          ]
                      ).map((unit) => (
                        <TouchableOpacity
                          key={unit || "none"}
                          style={[
                            styles.unitOption,
                            field.unit === unit && styles.unitOptionSelected,
                          ]}
                          onPress={() => {
                            updateSpecField(index, "unit", unit);
                            setActiveUnitDropdown(null);
                          }}
                        >
                          <span
                            style={webStyle([
                              styles.unitOptionText,
                              field.unit === unit &&
                                styles.unitOptionTextSelected,
                            ])}
                          >
                            {unit ? unit : "None"}
                          </span>
                          {field.unit === unit && (
                            <Icon name="check" size={14} color="#8B5CF6" />
                          )}
                        </TouchableOpacity>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
            <span style={webStyle(styles.helperText)}>
              Add product specifications. Rate and price use unit selectors.
            </span>
          </div>
        </div>

        {/* Parties Section */}
        <div style={webStyle(styles.section)}>
          <div style={webStyle(styles.sectionHeader)}>
            <Icon name="account-multiple-outline" size={22} color="#8B5CF6" />
            <span style={webStyle(styles.sectionTitle)}>Parties</span>
            {selectedPartys.length > 0 && (
              <div style={webStyle(styles.countBadge)}>
                <span style={webStyle(styles.countText)}>{selectedPartys.length}</span>
              </div>
            )}
          </div>
          <div style={webStyle(styles.sectionContent)}>
            <div style={webStyle(styles.partyInfoHeader)}>
              <div style={webStyle({ flex: 1 })}>
                <span style={webStyle(styles.partySectionLabel)}>
                  Select product parties (Required)
                </span>
                <span style={webStyle(styles.partySectionSubtext)}>
                  Select multiple parties from the list
                </span>
              </div>
              <TouchableOpacity
                style={styles.selectPartyButton}
                onPress={() => setShowPartysModal(true)}
              >
                <Icon name="chevron-right" size={20} color="#8B5CF6" />
              </TouchableOpacity>
            </div>

            {selectedPartys.length > 0 ? (
              <div style={webStyle(styles.selectedPartiesContainer)}>
                <span style={webStyle(styles.selectedLabel)}>Selected Parties:</span>
                <ScrollView
                  horizontal
                  showsHorizontalScrollIndicator={false}
                  style={styles.selectedPartiesScroll}
                >
                  {selectedPartys.map((partyId) => {
                    const party = partys.find((p) => p.id === partyId);
                    return party ? (
                      <div key={party.id} style={webStyle(styles.selectedPartyCard)}>
                        <div style={webStyle(styles.partyCardHeader)}>
                          <Icon
                            name="account-circle"
                            size={20}
                            color="#8B5CF6"
                          />
                          <span style={webStyle(styles.partyCardName)}>
                            {party.name}
                          </span>
                        </div>
                        <TouchableOpacity
                          onPress={() => handlePartySelect(partyId)}
                          style={styles.removePartyCardButton}
                        >
                          <Icon name="close-circle" size={18} color="#EF4444" />
                        </TouchableOpacity>
                      </div>
                    ) : null;
                  })}
                </ScrollView>
              </div>
            ) : (
              <div style={webStyle(styles.emptyPartiesState)}>
                <Icon
                  name="account-multiple-outline"
                  size={48}
                  color="#D1D5DB"
                />
                <span style={webStyle(styles.emptyPartiesTitle)}>
                  No parties selected
                </span>
                <TouchableOpacity
                  style={styles.selectPartiesButton}
                  onPress={() => setShowPartysModal(true)}
                >
                  <Icon
                    name="account-multiple-plus"
                    size={18}
                    color="#FFFFFF"
                  />
                  <span style={webStyle(styles.selectPartiesButtonText)}>
                    Select Parties
                  </span>
                </TouchableOpacity>
              </div>
            )}
          </div>
        </div>

        {/* Party Selection Modal */}
        <KeyboardAwareModal
          visible={showPartysModal}
          animationType="slide"
          transparent={true}
          onRequestClose={() => setShowPartysModal(false)}
        >
          <div style={webStyle(styles.modalOverlay)}>
            <div style={webStyle(styles.modalContainer)}>
              <div style={webStyle(styles.modalHeader)}>
                <div style={webStyle({ flex: 1 })}>
                  <span style={webStyle(styles.modalTitle)}>Select Parties</span>
                  <span style={webStyle(styles.modalSubtitle)}>
                    Choose one or more parties
                  </span>
                </div>
                <TouchableOpacity
                  onPress={() => setShowPartysModal(false)}
                  style={styles.modalCloseButton}
                >
                  <Icon name="close" size={24} color="#6B7280" />
                </TouchableOpacity>
              </div>

              {/* Add New Party Button */}
              <TouchableOpacity
                style={styles.addNewPartyTopButton}
                onPress={() => {
                  setShowPartysModal(false);
                  router.push("/parties/add" as any);
                }}
              >
                <Icon name="account-plus" size={20} color="#FFFFFF" />
                <span style={webStyle(styles.addNewPartyTopButtonText)}>
                  Add New Party
                </span>
              </TouchableOpacity>

              <div style={webStyle(styles.searchSection)}>
                <div style={webStyle(styles.searchContainer)}>
                  <Icon name="magnify" size={20} color="#8B5CF6" />
                  <TextInput
                    style={styles.searchInput}
                    placeholder="Search by name, mobile..."
                    value={partySearchQuery}
                    onChangeText={handlePartySearch}
                    placeholderTextColor="#9CA3AF"
                    autoCapitalize="none"
                  />
                  {partySearchQuery ? (
                    <TouchableOpacity onPress={handleClearPartySearch}>
                      <Icon name="close-circle" size={20} color="#9CA3AF" />
                    </TouchableOpacity>
                  ) : null}
                </div>
              </div>

              <div style={webStyle(styles.selectedCountCard)}>
                <div style={webStyle(styles.selectedCountInfo)}>
                  <div style={webStyle(styles.selectedCountBadge)}>
                    <span style={webStyle(styles.selectedCountNumber)}>
                      {selectedPartys.length}
                    </span>
                  </div>
                  <span style={webStyle(styles.selectedCountLabel)}>
                    parties selected
                  </span>
                </div>
                {selectedPartys.length > 0 && (
                  <TouchableOpacity
                    onPress={() => setSelectedPartys([])}
                    style={styles.clearSelectionButton}
                  >
                    <Icon name="close-circle" size={16} color="#EF4444" />
                    <span style={webStyle(styles.clearSelectionText)}>Clear</span>
                  </TouchableOpacity>
                )}
              </div>

              {partys.length === 0 && fetchingPartys ? (
                <div style={webStyle(styles.loadingState)}>
                  <ActivityIndicator size="large" color="#8B5CF6" />
                  <span style={webStyle(styles.loadingStateText)}>
                    Loading parties...
                  </span>
                </div>
              ) : (
                <FlatList
                  data={partys}
                  keyExtractor={(item, index) => `${item.id}_${index}`}
                  renderItem={({ item }) => {
                    const isSelected = selectedPartys.includes(item.id!);
                    return (
                      <TouchableOpacity
                        key={item.id}
                        style={[
                          styles.partyListItem,
                          isSelected && styles.partyListItemSelected,
                        ]}
                        onPress={() => handlePartySelect(item.id!)}
                      >
                        <div id={item.id} style={webStyle(styles.partyListItemContent)}>
                          <div
                            style={webStyle([
                              styles.selectionIndicator,
                              isSelected && styles.selectionIndicatorSelected,
                            ])}
                          >
                            {isSelected && (
                              <Icon name="check" size={14} color="#FFFFFF" />
                            )}
                          </div>
                          <div style={webStyle({ flex: 1 })}>
                            <span style={webStyle(styles.partyName)}>
                              {item.name}
                            </span>
                            {item.mobile && (
                              <span style={webStyle(styles.partyMobile)}>
                                {item.mobile}
                              </span>
                            )}
                          </div>
                        </div>
                      </TouchableOpacity>
                    );
                  }}
                  ListEmptyComponent={
                    <div style={webStyle(styles.emptyState)}>
                      <Icon name="account-group" size={48} color="#D1D5DB" />
                      <span style={webStyle(styles.emptyStateTitle)}>
                        No parties found
                      </span>
                    </div>
                  }
                  contentContainerStyle={{ paddingBottom: 20 }}
                />
              )}

              <div style={webStyle(styles.modalFooter)}>
                <TouchableOpacity
                  style={styles.cancelModalButton}
                  onPress={() => setShowPartysModal(false)}
                >
                  <span style={webStyle(styles.cancelModalText)}>Cancel</span>
                </TouchableOpacity>
                <TouchableOpacity
                  style={[
                    styles.confirmButton,
                    selectedPartys.length === 0 && styles.confirmButtonDisabled,
                  ]}
                  onPress={() => {
                    if (selectedPartys.length > 0) {
                      setShowPartysModal(false);
                    }
                  }}
                  disabled={selectedPartys.length === 0}
                >
                  <Icon name="check-circle" size={18} color="#FFFFFF" />
                  <span style={webStyle(styles.confirmButtonText)}>
                    Confirm ({selectedPartys.length})
                  </span>
                </TouchableOpacity>
              </div>
            </div>
          </div>
        </KeyboardAwareModal>

        {/* Action Buttons */}
        <div style={webStyle(styles.actionButtons)}>
          <TouchableOpacity
            style={styles.cancelButton}
            onPress={() => router.back()}
            disabled={loading}
          >
            <span style={webStyle(styles.cancelButtonText)}>Cancel</span>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={handleSubmit}
            disabled={loading || imageProcessing || selectedPartys.length === 0}
            activeOpacity={0.7}
            style={[
              styles.submitButton,
              (loading || imageProcessing || selectedPartys.length === 0) &&
                styles.submitButtonDisabled,
            ]}
          >
            {loading ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <span style={webStyle(styles.submitButtonText)}>
                {isEditMode ? "Save Changes" : "Create Product"}
              </span>
            )}
          </TouchableOpacity>
        </div>

        <div style={webStyle(styles.footer)}>
          <span style={webStyle(styles.footerText)}>
            Fields marked with <span style={webStyle(styles.required)}>*</span> are
            required
          </span>
        </div>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  scrollContent: {
    paddingBottom: isSmallScreen ? 76 : 100,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#6B7280",
  },
  infoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EDE9FE",
    padding: isSmallScreen ? 10 : 12,
    marginHorizontal: isSmallScreen ? 10 : 16,
    marginTop: isSmallScreen ? 10 : 16,
    borderRadius: 8,
    gap: 8,
  },
  infoText: {
    flex: 1,
    fontSize: 13,
    color: "#5B21B6",
    fontWeight: "500",
  },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEE2E2",
    padding: isSmallScreen ? 10 : 12,
    marginHorizontal: isSmallScreen ? 10 : 16,
    marginTop: 8,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#EF4444",
    gap: 8,
  },
  errorBannerText: {
    flex: 1,
    fontSize: 13,
    color: "#7F1D1D",
  },
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D1FAE5",
    padding: isSmallScreen ? 10 : 12,
    marginHorizontal: isSmallScreen ? 10 : 16,
    marginTop: 8,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#10B981",
    gap: 8,
  },
  successBannerText: {
    flex: 1,
    fontSize: 13,
    color: "#065F46",
  },
  section: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: isSmallScreen ? 10 : 16,
    marginTop: isSmallScreen ? 10 : 16,
    borderRadius: isSmallScreen ? 10 : 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: isSmallScreen ? 12 : 16,
    backgroundColor: "#F9FAFB",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  sectionTitle: {
    fontSize: isSmallScreen ? 15 : 16,
    fontWeight: "600",
    color: "#1F2937",
    marginLeft: 10,
    flex: 1,
  },
  sectionContent: {
    padding: isSmallScreen ? 12 : 16,
    gap: 4,
  },
  formGroup: {
    marginBottom: 4,
  },
  row: {
    flexDirection: isSmallScreen ? "column" : "row",
  },
  rowSpaced: {
    flexDirection: isSmallScreen ? "column" : "row",
    gap: isSmallScreen ? 0 : 12,
    marginBottom: 0,
  },
  halfField: {
    flex: 1,
    minWidth: 0,
  },
  countBadge: {
    backgroundColor: "#8B5CF6",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 24,
    alignItems: "center",
  },
  countText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 11,
  },
  mediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  mediaItem: {
    width: isSmallScreen ? (width - 44) / 3 : (width - 64) / 3,
    aspectRatio: 1,
    borderRadius: 8,
    overflow: "hidden",
    position: "relative",
    backgroundColor: "#F3F4F6",
  },
  mediaImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  removeMediaButton: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "rgba(239, 68, 68, 0.9)",
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  mediaIndex: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    color: "#FFFFFF",
    fontSize: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },
  emptyMedia: {
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#D1D5DB",
    borderRadius: 8,
    backgroundColor: "#F9FAFB",
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: "500",
    color: "#6B7280",
    marginTop: 8,
  },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#D1D5DB",
    borderRadius: 8,
    backgroundColor: "#F9FAFB",
    gap: 8,
  },
  uploadText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#8B5CF6",
  },
  addButton: {
    backgroundColor: "#8B5CF6",
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  specFieldContainer: {
    marginBottom: 14,
    position: "relative",
  },
  specFieldHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  specFieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    textTransform: "capitalize",
  },
  removeSpecBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FEF2F2",
  },
  specFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  specInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    color: "#1F2937",
    backgroundColor: "#FAFAFA",
  },
  unitBadge: {
    backgroundColor: "#F5F3FF",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#DDD6FE",
  },
  unitBadgeText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#8B5CF6",
  },
  unitPickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#F5F3FF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  unitPickerText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6B7280",
  },
  unitDropdown: {
    marginTop: 4,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    zIndex: 1000,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  unitOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  unitOptionSelected: {
    backgroundColor: "#F5F3FF",
  },
  unitOptionText: {
    fontSize: 14,
    color: "#4B5563",
  },
  unitOptionTextSelected: {
    color: "#8B5CF6",
    fontWeight: "600",
  },
  helperText: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 8,
  },
  partyInfoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    padding: 12,
    backgroundColor: "#F5F3FF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EDE9FE",
  },
  partySectionLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#5B21B6",
    marginBottom: 4,
  },
  partySectionSubtext: {
    fontSize: 13,
    color: "#7C3AED",
  },
  selectPartyButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#DDD6FE",
  },
  selectedPartiesContainer: {
    marginBottom: 16,
  },
  selectedLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 12,
  },
  selectedPartiesScroll: {
    flexDirection: "row",
  },
  selectedPartyCard: {
    flexDirection: "row",
    alignItems: "center",
    width: 160,
    marginRight: 12,
    padding: 12,
    backgroundColor: "#F0FDF4",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DCFCE7",
  },
  partyCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 8,
  },
  partyCardName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#166534",
    flex: 1,
  },
  removePartyCardButton: {
    marginLeft: 4,
  },
  emptyPartiesState: {
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#E5E7EB",
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
  },
  emptyPartiesTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4B5563",
    marginTop: 12,
    marginBottom: 16,
  },
  selectPartiesButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8B5CF6",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
  },
  selectPartiesButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: isSmallScreen ? 12 : 20,
  },
  modalContainer: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "86%",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#6B7280",
  },
  modalCloseButton: {
    padding: 4,
  },
  addNewPartyTopButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 20,
    marginTop: 12,
    paddingVertical: isSmallScreen ? 11 : 14,
    backgroundColor: "#8B5CF6",
    borderRadius: 12,
  },
  addNewPartyTopButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  searchSection: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#1F2937",
  },
  selectedCountCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    marginHorizontal: 20,
    marginBottom: 8,
    backgroundColor: "#F5F3FF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DDD6FE",
  },
  selectedCountInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  selectedCountBadge: {
    backgroundColor: "#8B5CF6",
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  selectedCountNumber: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 14,
  },
  selectedCountLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#5B21B6",
  },
  clearSelectionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#FEE2E2",
    borderRadius: 6,
  },
  clearSelectionText: {
    color: "#EF4444",
    fontSize: 13,
    fontWeight: "500",
  },
  loadingState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  loadingStateText: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 12,
  },
  partyListItem: {
    paddingVertical: isSmallScreen ? 11 : 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  partyListItemSelected: {
    backgroundColor: "#F5F3FF",
  },
  partyListItemContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  selectionIndicator: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#D1D5DB",
    justifyContent: "center",
    alignItems: "center",
  },
  selectionIndicatorSelected: {
    backgroundColor: "#8B5CF6",
    borderColor: "#8B5CF6",
  },
  partyName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1F2937",
  },
  partyMobile: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  footerLoader: {
    padding: isSmallScreen ? 12 : 16,
    alignItems: "center",
  },
  loadMoreBtn: {
    alignItems: "center",
    padding: 14,
    backgroundColor: "#F9FAFB",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  loadMoreText: {
    fontSize: 14,
    color: "#8B5CF6",
    fontWeight: "600",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4B5563",
    marginTop: 12,
  },
  modalFooter: {
    flexDirection: "row",
    padding: 20,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  cancelModalButton: {
    flex: 1,
    paddingVertical: isSmallScreen ? 11 : 14,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelModalText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6B7280",
  },
  confirmButton: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: isSmallScreen ? 11 : 14,
    backgroundColor: "#8B5CF6",
    borderRadius: 10,
    gap: 8,
  },
  confirmButtonDisabled: {
    backgroundColor: "#9CA3AF",
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  actionButtons: {
    flexDirection: "row",
    padding: isSmallScreen ? 12 : 16,
    marginTop: 16,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: isSmallScreen ? 11 : 14,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6B7280",
  },
  submitButton: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: isSmallScreen ? 11 : 14,
    backgroundColor: "#8B5CF6",
    borderRadius: 10,
    gap: 8,
  },
  submitButtonDisabled: {
    backgroundColor: "#9CA3AF",
    opacity: 0.6,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  footer: {
    paddingHorizontal: 16,
    paddingBottom: 20,
    alignItems: "center",
  },
  footerText: {
    fontSize: 13,
    color: "#6B7280",
  },
  required: {
    color: "#EF4444",
  },
});

export default ProductForm;
